### ISSUE TITLE
How to i use only Adwaita mouse cursor for all Exodia themes?

### ISSUE THREAD

**Issue by tapsu01** [Exodia-OS/exodia-theming#1]
I want to use Adwaita mouse cursor fro all Exodia themes. I used "Customize Look and Feel" to set default cursor but it's not working

**Comment by mmsaeed509** [comment]
## change for current theme

edit `~/.xsettingsd`
change value of `Gtk/CursorThemeName "WineTrix"` change `WineTrix` only
   
![Screenshot_2022-10-08-01-50-03_3840x1080](https://user-images.githubusercontent.com/62524855/194706676-ce0df651-677f-480b-a13a-e77a42585a0c.png)


open terminal `xsettingsd &`


## change for all themes

edit `~/.config/bspwm/rofi/bin/themes` 

![Screenshot_2022-10-08-01-54-40_3840x1080](https://user-images.githubusercontent.com/62524855/194706310-ba9c7a61-1740-4b87-a3fb-4cdc77ac78a4.png)

as mentioned above in the snapshot the 5th argument for the cursor theme
you need to change it in all themes to 
to apply changes you need to edit `~/.xsettingsd` & open terminal `xsettingsd &` or  <kbd>ctrl+alt+t</kbd> and select your fav theme
